services:
  - type: web
    name: whatsupcloud-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: CLIENT_URL
        sync: false
